"""Signal-lab package for lightweight copy-trade signal exploration."""

from .signal_engines import PositionSignalEngine, archetype_sets, compute_hold_time_metrics, position_report
from .signal_lib import (
    apply_composite_score,
    apply_rank_transformer,
    bootstrap_ic,
    coincidence_rate,
    compute_event_ic,
    compute_event_ir,
    compute_optimal_weights,
    cs_rank,
    evaluate_strategy,
    fit_rank_transformer,
    fit_roi_residualizer,
    hit_rate,
    ic_correlation_matrix,
    residualized_roi,
    signal_quality_report,
)
from .stage1 import (
    DEFAULT_COPY_RULES,
    DEFAULT_FRESH_SIGNAL_KINDS,
    DEFAULT_SIGNAL_KINDS,
    Stage1Workspace,
    attach_position_signal_panel,
    build_composite_scores,
    build_stage1_workspace,
    evaluate_signal_panel,
    evaluate_threshold_grid,
    rank_normalize_splits,
    select_copy_wallets,
    summarize_workspace,
)

__all__ = [
    "DEFAULT_COPY_RULES",
    "DEFAULT_FRESH_SIGNAL_KINDS",
    "DEFAULT_SIGNAL_KINDS",
    "PositionSignalEngine",
    "Stage1Workspace",
    "apply_composite_score",
    "apply_rank_transformer",
    "archetype_sets",
    "attach_position_signal_panel",
    "bootstrap_ic",
    "build_composite_scores",
    "build_stage1_workspace",
    "coincidence_rate",
    "compute_event_ic",
    "compute_event_ir",
    "compute_hold_time_metrics",
    "compute_optimal_weights",
    "cs_rank",
    "evaluate_signal_panel",
    "evaluate_strategy",
    "evaluate_threshold_grid",
    "fit_rank_transformer",
    "fit_roi_residualizer",
    "hit_rate",
    "ic_correlation_matrix",
    "position_report",
    "rank_normalize_splits",
    "residualized_roi",
    "select_copy_wallets",
    "signal_quality_report",
    "summarize_workspace",
]
